name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
      airbyte_tables:
        +tags: normalized_tables
        +materialized: ephemeral
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
      airbyte_final:
        +tags: normalized_tables
        +materialized: table    
        schema: final    
vars:
  dbt_utils_dispatch_list:
  - airbyte_utils
  json_column: _airbyte_data
  models_to_source:
    entries_ab1: dbo._airbyte_raw_entries
    entries_ab2: dbo._airbyte_raw_entries
    entries_ab3: dbo._airbyte_raw_entries
    entries: dbo._airbyte_raw_entries
    members_ab1: dbo._airbyte_raw_members
    members_ab2: dbo._airbyte_raw_members
    members_ab3: dbo._airbyte_raw_members
    members: dbo._airbyte_raw_members
    projects_ab1: dbo._airbyte_raw_projects
    projects_ab2: dbo._airbyte_raw_projects
    projects_ab3: dbo._airbyte_raw_projects
    projects: dbo._airbyte_raw_projects
    entries_timeinterval_ab1: dbo._airbyte_raw_entries
    entries_timeinterval_ab2: dbo._airbyte_raw_entries
    entries_timeinterval_ab3: dbo._airbyte_raw_entries
    entries_timeinterval: dbo._airbyte_raw_entries
    members_settings_ab1: dbo._airbyte_raw_members
    members_settings_ab2: dbo._airbyte_raw_members
    members_settings_ab3: dbo._airbyte_raw_members
    members_settings: dbo._airbyte_raw_members
    projects_estimate_ab1: dbo._airbyte_raw_projects
    projects_estimate_ab2: dbo._airbyte_raw_projects
    projects_estimate_ab3: dbo._airbyte_raw_projects
    projects_estimate: dbo._airbyte_raw_projects
    projects_hourlyrate_ab1: dbo._airbyte_raw_projects
    projects_hourlyrate_ab2: dbo._airbyte_raw_projects
    projects_hourlyrate_ab3: dbo._airbyte_raw_projects
    projects_hourlyrate: dbo._airbyte_raw_projects
    projects_memberships_ab1: dbo._airbyte_raw_projects
    projects_memberships_ab2: dbo._airbyte_raw_projects
    projects_memberships_ab3: dbo._airbyte_raw_projects
    projects_memberships: dbo._airbyte_raw_projects
    projects_timeestimate_ab1: dbo._airbyte_raw_projects
    projects_timeestimate_ab2: dbo._airbyte_raw_projects
    projects_timeestimate_ab3: dbo._airbyte_raw_projects
    projects_timeestimate: dbo._airbyte_raw_projects
    members_settin__summaryreportsettings_ab1: dbo._airbyte_raw_members
    members_settin__summaryreportsettings_ab2: dbo._airbyte_raw_members
    members_settin__summaryreportsettings_ab3: dbo._airbyte_raw_members
    members_settin__summaryreportsettings: dbo._airbyte_raw_members
