config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      database: clockify
      driver: ODBC Driver 17 for SQL Server
      password: '#Password123'
      port: 1433
      schema: dbo
      server: localhost
      threads: 8
      type: sqlserver
      user: sa
  target: prod
