version: 2
sources:
- name: dbo
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_test_2_entries
  - name: _airbyte_raw_test_2_members
  - name: _airbyte_raw_test_2_projects
