version: 2
sources:
- name: dbo
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_entries
  - name: _airbyte_raw_members
  - name: _airbyte_raw_projects
